### ISSUE TITLE
In-App Updates

### ISSUE THREAD

**Issue by mvidailhet** [microsoft/appcenter-sdk-cordova#141]
**Is your feature request related to a problem? Please describe.**
I want to force users to download the latest version of the app directly in the app

**Describe the solution you'd like**
The same as on Android or iOS, show a popup telling to update the app

**Describe alternatives you've considered**
Manually connect to the app center api and check if the current app is the latest

**Additional context**
I'm developing my app with Capacitor (which works with the cordova-sdk)

**Comment by russelarms** [comment]
Hi there, thanks for opening the feature request.
Unfortunately, we don't have an ETA for it yet, since the AppCenter team is focused on improving reliability and stability until mid-2021 https://github.com/microsoft/appcenter#planning.

Please vote for this feature request in the main repo: https://github.com/microsoft/appcenter/issues/1312

**Comment by mvidailhet** [comment]
Hi @russelarms !
Thank you for your reactivity and your answer.

I understand perfectly that Cordova Capacitor is not your main concern atm. I think I'll be able to do what I need with the api.

But why close the issue ? 

I made it because I didn't see any on the subject. It will help others see that you still have it it mind.

**Comment by russelarms** [comment]
Hi @mvidailhet, the main App Center repository has a higher priority in the question of duplicated feature requests: https://github.com/microsoft/appcenter/issues/1312
