### ISSUE TITLE
Expose values of install and session IDs to JavaScript

### ISSUE THREAD

**Issue by irnc** [Microsoft/appcenter-sdk-cordova#32]
We want to correlate events happening inside mobile app with events happening on server during request handling.

For that we use App Center to gather events from mobile app and export them to Application Insights. We use the same Application Insights resource for export from App Center and for reporting from server, so we could see events from both sources correlated to each other.

In order to implement correlation, we need to pass install ID and session ID to server, for usage as user ID and session ID respectively.

Install ID could be exposed as value of `[MSAppCenter installId]` and session ID as `[MSSessionContext sessionId]`.

Is it a right way to correlate App Center events with server-generated items in Application Insights? Would you like to see pull request with those values exposed?

**Comment by elamalani** [comment]
@irnc Thanks for using App Center. I will let an expert in our product team comment if its the right way to correlate App Center events with server generated events in AI. App Center SDK only supports a getter for InstallID. Currently, there is no way to get a SessionID and we need to decide within our team if we want to expose it.

**Comment by kpiteira** [comment]
I have not tested that but it looks like a good way of achieving the goal. Maybe even generating a correlation id which could be a hash of installID/sessionID so that you're not dependent on these specific values, and could allow you to change the way you do correlation by basing only on 1 ID (guid type or something else)

**Comment by sergey-akhalkov** [comment]
Hi @elamalani, could you please let me know if we have any updates on this:
>@irnc Thanks for using App Center. I will let an expert in our product team comment if its the right way to correlate App Center events with server generated events in AI. App Center SDK only supports a getter for InstallID. Currently, there is no way to get a SessionID and we need to decide within our team if we want to expose it.

We are going to maintain this repo duting this week, so we can probably implement this feature if it makes sense.

**Comment by annakocheshkova** [comment]
Hi @irnc, just an update that `getInstallId` method is now available via `AppCenter.getInstallId()`. Please update to the [0.1.5](https://github.com/Microsoft/appcenter-sdk-cordova/releases/tag/0.1.5).

As of `sessionId`, I'm afraid we won't be able to provide such a method, because we can not expose any functionality that's not a part of the public [App Center SDK API](https://github.com/Microsoft/AppCenter-SDK-Apple/blob/develop/AppCenter/AppCenter/MSAppCenter.h).

**Comment by irnc** [comment]
Thanks for the update!

> As of sessionId, I'm afraid we won't be able to provide such a method, because we can not expose any functionality that's not a part of the public App Center SDK API.

IIRC, without session ID exposed I couldn't link events between App Center and Application Insights. I would review our progress in this direction and create issues in native App Center SDKs if needed.

**Comment by annakocheshkova** [comment]
@irnc ok, I'm closing this for now, feel free to reopen any time!

**Comment by neerajyadav** [comment]
Any updates on exposing sessionId via client sdk? I want to store user sessions information on server so that when user says my application crashed or this error happened, I can precisely get logs of the session user is talking about.
